package com.nidyaber.fuckdsmanger

/* 宿主灰度开关表（原 UI 的「灰度选项管理」页）——**生成物，别手改**
   来源：gm/GmDialog 的 (键, 标签, 类型) 三连 + 那条按 \n 分隔的说明串
   键已带 kv_remote_settings_ 前缀的按原样用（看 pfx 标记） */
enum class GrayType { B, I, S, L }

data class Gray(val key: String, val label: String, val hint: String,
                val type: GrayType, val pfx: Boolean)

object GrayTable {
    val items = listOf(
        Gray("voice_input_enabled", "语音输入", "开关：输入框显示麦克风；关闭：完全隐藏语音入口", GrayType.B, false),
        Gray("input_default_voice", "默认音色", "语音识别的默认语言/音色标识，如 zh-CN", GrayType.B, false),
        Gray("input_view_voice_gesture_duration_ms", "语音手势时长", "按住说话手势的识别时长，单位毫秒", GrayType.I, false),
        Gray("record_empty_detect_time_ms", "空录音检测", "录到多少毫秒静音就判定为“空录音”", GrayType.I, false),
        Gray("record_stop_delay_ms", "录音停止延迟", "松手后再录多久才停，防止截断尾音", GrayType.I, false),
        Gray("max_duration_ms", "最长录音时长", "单次录音上限，超时自动停止", GrayType.I, false),
        Gray("opus_bitrate", "Opus 码率", "语音上传的 Opus 编码码率，越高越清晰也越费流量", GrayType.I, false),
        Gray("deep_think_button_suffix", "深度思考后缀", "深度思考按钮后面拼的文字，如 R1", GrayType.S, false),
        Gray("conversation_search_enabled", "会话搜索", "开关：会话内可搜索历史消息", GrayType.B, false),
        Gray("search_state_on_login", "登录后搜索态", "搜索态：填 on=默认开 / off=默认关，留空=跟随下发", GrayType.S, false),
        Gray("search_state_on_launch", "启动后搜索态", "搜索态：填 on / off，留空=跟随下发（冷启动）", GrayType.S, false),
        Gray("allow_parallel_streams", "并发流", "开关：AI 回复中也能直接发新消息（多流并发）", GrayType.B, false),
        Gray("interrupt_and_send_enabled", "打断并发", "开关：发新消息会立即打断当前回复", GrayType.B, false),
        Gray("allow_file_with_search", "文件+搜索", "开关：联网搜索时可同时带文件一起问", GrayType.B, false),
        Gray("sse_smooth_follow", "流式平滑跟随", "开关：流式输出时页面平滑跟随；关闭则直接跳到底", GrayType.B, false),
        Gray("normal_history_and_file_token_limit", "普通上下文上限", "普通模式带上下文的最大 token 数，超了会截断", GrayType.I, false),
        Gray("r1_history_and_file_token_limit", "R1 上下文上限", "R1 深度思考模式的上下文 token 上限", GrayType.I, false),
        Gray("completion_request_timeout_ms", "补全超时", "等 AI 回复的超时毫秒数，超时断开", GrayType.I, false),
        Gray("regenerate_request_timeout_ms", "重新生成超时", "点“重新生成”后的请求超时", GrayType.I, false),
        Gray("hif_max_retry_interval_secs", "重试间隔(s)", "请求失败后重试的最大间隔（指数退避上限）", GrayType.I, false),
        Gray("hcaptcha_enabled", "hCaptcha 验证", "开关：登录/注册时弹 hCaptcha 人机验证", GrayType.B, false),
        Gray("enable_google_sign_in_captcha", "Google 登录验证", "开关：Google 登录也要过人机验证", GrayType.B, false),
        Gray("one_tap_login_enabled", "一键登录", "开关：支持运营商一键登录", GrayType.B, false),
        Gray("hide_assistant_avatar", "隐藏助手头像", "开关：AI 回复旁不显示头像", GrayType.B, false),
        Gray("select_text_without_markdown_syntax", "选中去MD语法", "开关：选中文本时自动去掉 ** 等 MD 符号", GrayType.B, false),
        Gray("enable_webview_content_report", "WebView 上报", "开关：WebView 内容上报做安全检测", GrayType.B, false),
        Gray("picture_compress_format", "图片压缩格式", "上传图片压缩成 webp / jpeg 等", GrayType.S, false),
        Gray("support_center_url", "客服中心地址", "打开“帮助与反馈”跳转的客服地址", GrayType.S, false),
        Gray("query_files_time_interval", "文件轮询间隔", "轮询文件解析状态的间隔毫秒", GrayType.I, false),
        Gray("markdown_top_level_node_limit", "MD 节点上限", "单条消息最多渲染多少顶层 MD 节点，防卡死", GrayType.I, false),
        Gray("pow_prefetch_count", "PoW 预取数", "提前缓存多少个 PoW 令牌", GrayType.I, false),
        Gray("session_prefetch_count", "会话预取数", "提前缓存多少个会话", GrayType.I, false),
        Gray("pow_prefetch", "PoW 预取开关", "开关：提前算好 PoW 令牌，发消息更快", GrayType.B, false),
        Gray("session_prefetch", "会话预取开关", "开关：提前拉取会话，列表秒开", GrayType.B, false),
        Gray("continue_request_timeout_ms", "继续生成超时", "“继续生成”请求的超时毫秒", GrayType.I, false),
        Gray("resume_request_timeout_ms", "恢复生成超时", "“断点续传”请求的超时毫秒", GrayType.I, false),
        Gray("edit_request_timeout_ms", "编辑请求超时", "编辑消息后重发的超时毫秒", GrayType.I, false),
        Gray("auto_resume_request_timeout_ms", "自动续传超时", "自动续传单次请求的超时毫秒", GrayType.I, false),
        Gray("auto_resume_max_time_ms", "自动续传窗口", "断流后最多在多长时间内自动续传", GrayType.I, false),
        Gray("auto_resume_interval_ms", "自动续传间隔", "自动续传的重试间隔毫秒", GrayType.I, false),
        Gray("launch_clean_session_interval_seconds", "启动清理间隔(s)", "启动时多久清理一次空会话（秒）", GrayType.I, false),
        Gray("pinned_session_limit", "置顶会话上限", "最多能置顶几个会话", GrayType.I, false),
        Gray("max_upload_file_size", "最大上传大小", "单个文件大小上限（字节），超了不让传", GrayType.I, false),
        Gray("max_input_file_count", "最大输入文件数", "一次最多选几个文件上传", GrayType.I, false),
        Gray("sse_auto_scroll_one_screen", "自动滚动一屏", "开关：自动滚动每次只滚一屏", GrayType.B, false),
        Gray("sse_auto_scroll_smooth_stiffness", "平滑滚动刚度", "平滑滚动刚度（整数，默认 50，越大越跟手）", GrayType.I, false),
        Gray("optimize_markdown", "优化 Markdown", "开关：启用 Markdown 渲染性能优化", GrayType.B, false),
        Gray("disable_single_dollar_latex", "禁用单\$LaTeX", "开关：单个 \$ 不再当公式，避免误渲染", GrayType.B, false),
        Gray("show_new_chat_button_above_input", "输入框上方新会话", "开关：输入框上方显示“新对话”按钮", GrayType.B, false),
        Gray("copy_text_without_markdown_syntax", "复制去 MD 语法", "开关：复制时自动去掉 MD 符号", GrayType.B, false),
        Gray("search_state_on_manually_created_chat", "手动新建搜索态", "搜索态：填 on / off，留空=跟随下发（手动新建会话）", GrayType.S, false),
        Gray("search_state_on_automatically_created_chat", "自动新建搜索态", "搜索态：填 on / off，留空=跟随下发（自动新建会话）", GrayType.S, false),
        Gray("should_use_sm_device_id", "使用数美设备 ID", "开关：风控使用数美设备指纹 ID", GrayType.B, false),
        Gray("dead_link_detection", "死链检测", "开关：检测消息里的失效链接", GrayType.B, false),
        Gray("gcy_enabled", "观测云上报", "开关：埋点数据上报到观测云（第三方监控）", GrayType.B, false),
        Gray("ds_settings_enabled", "DS 设置开关", "DeepSeek 客户端设置模块总开关", GrayType.B, false),
        Gray("volcengine_enabled", "火山引擎开关", "开关：使用火山引擎相关服务", GrayType.S, false),
        Gray("sm_pass_code_type", "验证码类型", "短信验证码的样式/类型", GrayType.S, false),
        Gray("edit_menu_item_config", "编辑菜单配置", "编辑菜单项配置，JSON 字符串", GrayType.I, false),
        Gray("files_host", "文件服务域名", "文件服务接口域名", GrayType.S, false),
        Gray("sm_sdk_host", "数美 SDK 域名", "数美风控 SDK 的域名", GrayType.S, false),
        Gray("android_apk_link", "安卓下载链接", "提示更新时跳转的安装包下载地址", GrayType.S, false),
        Gray("support_chat_file_exts", "支持文件后缀", "支持上传的文件后缀白名单，JSON 数组", GrayType.S, true),
        Gray("pow_header_paths", "PoW 头路径", "需要带 PoW 头的请求路径，JSON 数组", GrayType.S, true),
        Gray("authed_pow_functions", "PoW 功能列表", "需要 PoW 校验的功能列表，JSON 数组", GrayType.S, true),
        Gray("image_cache_invalidate_before", "图片缓存失效", "早于此时间戳的图片缓存全部失效（毫秒）", GrayType.L, true),
        Gray("camera_compress_ratio", "拍照压缩比", "拍照上传的图片压缩比，0~1 浮点", GrayType.I, true),
        Gray("photo_picker_compress_ratio", "相册压缩比", "从相册选图上传的压缩比，0~1 浮点", GrayType.I, true),
        Gray("search_state_trigger", "搜索触发器", "联网搜索触发条件配置，JSON 对象", GrayType.S, true),
        Gray("model_configs_v1", "模型配置表", "模型配置总表，JSON 数组（key 为 model_configs_v1）", GrayType.S, true),
        Gray("tts_connect_timeout_ms", "TTS 连接超时", "TTS 朗读连接超时毫秒，默认 5000", GrayType.I, false),
        Gray("tts_prebuffer_ms", "TTS 预缓冲", "TTS 起播前预缓冲毫秒，默认 240", GrayType.I, false),
        Gray("tts_resume_buffer_ms", "TTS 续播缓冲", "TTS 续播缓冲毫秒，默认 240", GrayType.I, false),
        Gray("tts_resume_max_times", "TTS 续播次数", "TTS 最多续播次数，-1 表示无限", GrayType.I, false),
        Gray("tts_resume_max_time_ms", "TTS 续播窗口", "TTS 续播总时长上限毫秒，-1 表示无限", GrayType.I, false),
        Gray("tts_resume_interval_ms", "TTS 续播间隔", "TTS 续播重试间隔毫秒，默认 1000", GrayType.I, false),
        Gray("tts_underrun_timeout_ms", "TTS 欠载超时", "TTS 欠载超时毫秒，默认 1000", GrayType.I, false),
        Gray("thinking_auto_fold_enabled", "思考自动折叠", "开关：深度思考过程自动折叠", GrayType.B, false),
        Gray("report_http_failure_paths", "失败上报路径", "失败上报的请求路径，JSON 数组", GrayType.S, true),
        Gray("alert", "公告弹窗", "服务端公告弹窗 JSON，清空即恢复下发值", GrayType.S, true),
        Gray("banner", "横幅", "服务端横幅 JSON，清空即恢复下发值", GrayType.S, true),
        Gray("key_auto_tts_enabled", "自动朗读总开关", "开关：自动朗读（TTS）总开关，默认关，关闭后无视服务端能力", GrayType.B, false),
        Gray("key_tts_voice_id", "朗读音色 ID", "朗读音色 ID（zh-CN 或具体音色标识）", GrayType.S, false),

        /* ── 以下：**宿主有、模块表里没有**的键（从宿主 MMKV / 反编译挖出来的）── */
        Gray("welcome_msg", "欢迎语", "服务端下发的开屏欢迎语", GrayType.S, false),
        Gray("welcome_msg_v1", "欢迎语 v1", "同上（v1）", GrayType.S, false),
        Gray("languages", "语言列表", "服务端下发的语言/多语言配置", GrayType.S, false),
    )
}
