package com.nidyaber.fuckdsmanger.glass;

/**
 * 液态玻璃 · **多方案 shader 表** 🐲
 *
 * <p>⚠️ <b>本文件由脚本生成，不要手改</b> ——
 * 跑 `python3 tools/gen_glass_shaders.py` 重新生成。
 * shader 正文以 `参考/液态玻璃多方案/*.agsl` 为准（逐字，不手抄）。
 *
 * <p>为什么要多方案：主人 2026-09-30 拍板「**再疯一点：多方案切换**」——
 * 社区里几个活跃实现思路差别很大，与其猜哪个好，不如**让用户切着试**。
 */
final class GmGlassShaders {

    private GmGlassShaders() {
    }

    /** Haze 式：sampleSize/materialOrigin/materialSize + over 合成 + 色散 */
    static final String HAZE =
              "uniform shader content;\n"
            + "// ── fdm 公共前奏（由 tools/gen_glass_shaders.py 注入）──\n"
            + "uniform float fdmCleanOn;\n"
            + "uniform float fdmCleanTol;\n"
            + "uniform float4 fdmCleanColor;\n"
            + "\n"
            + "half4 fdmSample(float2 p) {\n"
            + "    half4 c = content.eval(p);\n"
            + "    if (fdmCleanOn < 0.5) { return c; }\n"
            + "    float d = distance(float3(c.rgb), float3(fdmCleanColor.rgb));\n"
            + "    // 离背景色太远 ⇒ 认为是文字/图标 ⇒ 换成背景色\n"
            + "    return (d > fdmCleanTol) ? half4(half3(fdmCleanColor.rgb), c.a) : c;\n"
            + "}\n"
            + "\n"
            + "// ── 「边缘过渡」公共件（2026-10-02 主人：「颜色没有过渡也很生硬」）──\n"
            + "//   sd = 有符号距离（负值 = 内部、0 = 边缘）⇒ 颜色从边缘往里柔和衰减。\n"
            + "//   fdmFade   = 强度 0..1（滑杆）\n"
            + "//   fdmFadePx = 过渡距离（px）；「仅边缘」= 边缘带宽；「正常」= 按元素尺寸取。\n"
            + "uniform float fdmFade;\n"
            + "uniform float fdmFadePx;\n"
            + "\n"
            + "float fdmFadeFac(float sd) {\n"
            + "    float inner = clamp(-sd / max(fdmFadePx, 1.0), 0.0, 1.0);\n"
            + "    return 1.0 - fdmFade * inner;\n"
            + "}\n"
            + "// ──────────────────────────────────────────────\n"
            + "uniform float2 sampleSize;\n"
            + "uniform float2 materialOrigin;\n"
            + "uniform float2 materialSize;\n"
            + "uniform float4 cornerRadii;\n"
            + "uniform float refractionHeight;\n"
            + "uniform float refractionAmount;\n"
            + "uniform float depthEffect;\n"
            + "uniform float dispersion;\n"
            + "uniform float4 tintColor;\n"
            + "float radiusAt(float2 coord, float4 radii) {\n"
            + "    if (coord.x >= 0.0) {\n"
            + "        if (coord.y <= 0.0) return radii.y; else return radii.z;\n"
            + "    } else {\n"
            + "        if (coord.y <= 0.0) return radii.x; else return radii.w;\n"
            + "    }\n"
            + "}\n"
            + "float sdRoundedRect(float2 coord, float2 halfSize, float radius) {\n"
            + "    float2 cornerCoord = abs(coord) - (halfSize - float2(radius));\n"
            + "    float outside = length(max(cornerCoord, 0.0)) - radius;\n"
            + "    float inside = min(max(cornerCoord.x, cornerCoord.y), 0.0);\n"
            + "    return outside + inside;\n"
            + "}\n"
            + "float2 gradSdRoundedRect(float2 coord, float2 halfSize, float radius) {\n"
            + "    float2 cornerCoord = abs(coord) - (halfSize - float2(radius));\n"
            + "    if (cornerCoord.x >= 0.0 || cornerCoord.y >= 0.0) {\n"
            + "        return sign(coord) * normalize(max(cornerCoord, 0.0) + float2(0.0001));\n"
            + "    } else {\n"
            + "        float gradX = step(cornerCoord.y, cornerCoord.x);\n"
            + "        return sign(coord) * float2(gradX, 1.0 - gradX);\n"
            + "    }\n"
            + "}\n"
            + "float circleMap(float x) { return 1.0 - sqrt(max(1.0 - x * x, 0.0)); }\n"
            + "float2 clampSample(float2 c) {\n"
            + "    return clamp(c, float2(0.5), sampleSize - float2(0.5));\n"
            + "}\n"
            + "half4 main(float2 coord) {\n"
            + "    float2 matCoord = coord - materialOrigin;\n"
            + "    float2 halfSize = materialSize * 0.5;\n"
            + "    float2 centeredCoord = matCoord - halfSize;\n"
            + "    float radius = radiusAt(matCoord, cornerRadii);\n"
            + "    float sd = sdRoundedRect(centeredCoord, halfSize, radius);\n"
            + "    float gradRadius = min(radius * 1.5, min(halfSize.x, halfSize.y));\n"
            + "    float2 grad = normalize(\n"
            + "            gradSdRoundedRect(centeredCoord, halfSize, gradRadius)\n"
            + "            + depthEffect * normalize(centeredCoord + float2(0.0001)));\n"
            + "    float d = 0.0;\n"
            + "    if (sd < 0.0) {\n"
            + "        float t = clamp(1.0 + sd / max(refractionHeight, 0.001), 0.0, 1.0);\n"
            + "        d = circleMap(t) * refractionAmount;\n"
            + "    }\n"
            + "    float2 base = coord + d * grad;\n"
            + "    half4 cr = fdmSample(clampSample(base + dispersion * grad));\n"
            + "    half4 cg = fdmSample(clampSample(base));\n"
            + "    half4 cb = fdmSample(clampSample(base - dispersion * grad));\n"
            + "    float3 rgb = float3(float(cr.r), float(cg.g), float(cb.b));\n"
            + "    float aEff = tintColor.a * fdmFadeFac(sd);\n"
            + "    float3 outRgb = tintColor.rgb * aEff + rgb * (1.0 - aEff);\n"
            + "    return half4(half(outRgb.r), half(outRgb.g), half(outRgb.b), half(1.0));\n"
            + "}"
            ;

    /** Cloudy 式：距离场折射 + RGB 色散 + 四重镜面高光 + 抖动防色带 */
    static final String CLOUDY =
              "\n"
            + "uniform float2 resolution;\n"
            + "uniform float2 lensCenter;\n"
            + "uniform float2 lensSize;\n"
            + "uniform float cornerRadius;\n"
            + "uniform float refraction;\n"
            + "uniform float curve;\n"
            + "uniform float dispersion;\n"
            + "uniform float saturation;\n"
            + "uniform float contrast;\n"
            + "uniform float4 tint;\n"
            + "uniform float edge;\n"
            + "uniform float2 lightDir;\n"
            + "uniform float specStrength;\n"
            + "uniform float specPower;\n"
            + "uniform float specRimMix;     // body<->rim crossfade\n"
            + "uniform float specWidthPx;\n"
            + "uniform float specLightZ;\n"
            + "uniform float specDomeFrac;\n"
            + "uniform float specBodyPower;\n"
            + "uniform float specBodyGain;\n"
            + "uniform float specFocalK;      // focal-pool offset toward light (fraction of minHalf)\n"
            + "uniform float specPoolFrac;    // focal-pool radius (fraction of minHalf)\n"
            + "uniform float specPoolGain;    // focal-pool peak scale\n"
            + "uniform shader content;\n"
            + "// ── fdm 公共前奏（由 tools/gen_glass_shaders.py 注入）──\n"
            + "uniform float fdmCleanOn;\n"
            + "uniform float fdmCleanTol;\n"
            + "uniform float4 fdmCleanColor;\n"
            + "\n"
            + "half4 fdmSample(float2 p) {\n"
            + "    half4 c = content.eval(p);\n"
            + "    if (fdmCleanOn < 0.5) { return c; }\n"
            + "    float d = distance(float3(c.rgb), float3(fdmCleanColor.rgb));\n"
            + "    // 离背景色太远 ⇒ 认为是文字/图标 ⇒ 换成背景色\n"
            + "    return (d > fdmCleanTol) ? half4(half3(fdmCleanColor.rgb), c.a) : c;\n"
            + "}\n"
            + "\n"
            + "// ── 「边缘过渡」公共件（2026-10-02 主人：「颜色没有过渡也很生硬」）──\n"
            + "//   sd = 有符号距离（负值 = 内部、0 = 边缘）⇒ 颜色从边缘往里柔和衰减。\n"
            + "//   fdmFade   = 强度 0..1（滑杆）\n"
            + "//   fdmFadePx = 过渡距离（px）；「仅边缘」= 边缘带宽；「正常」= 按元素尺寸取。\n"
            + "uniform float fdmFade;\n"
            + "uniform float fdmFadePx;\n"
            + "\n"
            + "float fdmFadeFac(float sd) {\n"
            + "    float inner = clamp(-sd / max(fdmFadePx, 1.0), 0.0, 1.0);\n"
            + "    return 1.0 - fdmFade * inner;\n"
            + "}\n"
            + "// ──────────────────────────────────────────────\n"
            + "\n"
            + "const float SMOOTH_EDGE_PX = 1.5;\n"
            + "const float SEAM_BLEND_PX = 8.0;   // diagonal blend half-width (px); larger = softer interior crease\n"
            + "\n"
            + "// Signed distance to a box with rounded corners\n"
            + "// Negative = inside, Positive = outside, Zero = on boundary\n"
            + "float boxRoundedSDF(float2 p, float2 halfDim, float r) {\n"
            + "    float2 d = abs(p) - halfDim + float2(r);\n"
            + "    float exterior = length(max(d, 0.0));\n"
            + "    float interior = min(max(d.x, d.y), 0.0);\n"
            + "    return exterior + interior - r;\n"
            + "}\n"
            + "\n"
            + "// Outward-facing direction vector from the lens surface\n"
            + "float2 lensNormalDirection(float2 p, float2 halfDim, float r) {\n"
            + "    float2 d = abs(p) - halfDim + float2(r);\n"
            + "    float2 s = float2(p.x >= 0.0 ? 1.0 : -1.0, p.y >= 0.0 ? 1.0 : -1.0);\n"
            + "\n"
            + "    if (max(d.x, d.y) > 0.0) {\n"
            + "        return s * normalize(max(d, 0.0));\n"
            + "    }\n"
            + "    return d.x > d.y ? float2(s.x, 0.0) : float2(0.0, s.y);\n"
            + "}\n"
            + "\n"
            + "// Perceptual brightness (ITU-R BT.709 standard)\n"
            + "float toBrightness(half3 c) {\n"
            + "    return dot(c, half3(0.2126, 0.7152, 0.0722));\n"
            + "}\n"
            + "\n"
            + "// Color processing: vibrancy, intensity adjustment, and color overlay\n"
            + "half3 processColor(half3 src, float vibrancy, float intensity, float4 overlay) {\n"
            + "    float mono = toBrightness(src);\n"
            + "    half3 vibrant = half3(clamp(mix(half3(mono), src, vibrancy), 0.0, 1.0));\n"
            + "    half3 adjusted = half3(clamp((vibrant - 0.5) * intensity + 0.5, 0.0, 1.0));\n"
            + "    return mix(adjusted, half3(overlay.rgb), overlay.a);\n"
            + "}\n"
            + "\n"
            + "half4 main(float2 xy) {\n"
            + "    float2 halfDim = lensSize * 0.5;\n"
            + "    float r = min(cornerRadius, min(halfDim.x, halfDim.y));\n"
            + "\n"
            + "    float2 p = xy - lensCenter;\n"
            + "    float sdf = boxRoundedSDF(p, halfDim, r);\n"
            + "\n"
            + "    // Skip pixels outside the lens boundary\n"
            + "    if (sdf > SMOOTH_EDGE_PX) {\n"
            + "        return fdmSample(xy);\n"
            + "    }\n"
            + "\n"
            + "    float2 normal = lensNormalDirection(p, halfDim, r);\n"
            + "\n"
            + "    // Compute refracted sample position\n"
            + "    float2 sampleXY = xy;\n"
            + "    if (refraction > 0.0 && curve > 0.0) {\n"
            + "        float minDim = min(halfDim.x, halfDim.y);\n"
            + "        float depth = clamp(-sdf / (minDim * refraction), 0.0, 1.0);\n"
            + "        float curvature = 1.0 - depth;\n"
            + "        float bend = 1.0 - sqrt(1.0 - curvature * curvature);\n"
            + "        sampleXY = xy - bend * curve * minDim * normal;\n"
            + "    }\n"
            + "\n"
            + "    // RGB channel separation for prismatic effect\n"
            + "    half4 pixel;\n"
            + "    if (dispersion > 0.0) {\n"
            + "        float2 normP = p / halfDim;\n"
            + "        float2 shift = dispersion * normP * normP * normP * min(halfDim.x, halfDim.y) * 0.1;\n"
            + "\n"
            + "        float2 xyR = sampleXY - shift;\n"
            + "        float2 xyG = sampleXY;\n"
            + "        float2 xyB = sampleXY + shift;\n"
            + "\n"
            + "        float sdfR = boxRoundedSDF(xyR - lensCenter, halfDim, r);\n"
            + "        float sdfB = boxRoundedSDF(xyB - lensCenter, halfDim, r);\n"
            + "\n"
            + "        half4 gVal = fdmSample(xyG);\n"
            + "        half4 rVal = (sdfR <= 0.0) ? fdmSample(xyR) : gVal;\n"
            + "        half4 bVal = (sdfB <= 0.0) ? fdmSample(xyB) : gVal;\n"
            + "\n"
            + "        pixel = half4(rVal.r, gVal.g, bVal.b, gVal.a);\n"
            + "    } else {\n"
            + "        pixel = fdmSample(sampleXY);\n"
            + "    }\n"
            + "\n"
            + "    // Handle fully transparent samples\n"
            + "    if (pixel.a <= 0.0) {\n"
            + "        pixel = fdmSample(xy);\n"
            + "    }\n"
            + "\n"
            + "    pixel.rgb = processColor(pixel.rgb, saturation, contrast, float4(tint.rgb, tint.a * fdmFadeFac(sdf)));\n"
            + "\n"
            + "    // Specular highlight: 4 terms — focal pool (dual-axis moving hotspot) + body sheen + Blinn rim\n"
            + "    // glint + back-rim fill. The gate also tests specStrength, so NoGlow is bit-exact off.\n"
            + "    if (edge > 0.0 && specStrength > 0.0) {\n"
            + "        float2 lightVec = normalize(lightDir);\n"
            + "\n"
            + "        // Seam-free in-plane direction (specular only; refraction's 'normal' is untouched). The\n"
            + "        // rounded-rect interior is an L-inf field, so the true gradient is discontinuous along the\n"
            + "        // diagonal; blend it over SEAM_BLEND_PX.\n"
            + "        float2 d2 = abs(p) - halfDim + float2(r);\n"
            + "        float2 s2 = float2(p.x >= 0.0 ? 1.0 : -1.0, p.y >= 0.0 ? 1.0 : -1.0);\n"
            + "        float2 specDir2;\n"
            + "        if (max(d2.x, d2.y) > 0.0) {\n"
            + "            specDir2 = s2 * normalize(max(d2, 0.0));\n"
            + "        } else {\n"
            + "            // +1e-4 guards the dead-center normalize singularity.\n"
            + "            float w  = clamp(0.5 + 0.5 * (d2.x - d2.y) / SEAM_BLEND_PX, 0.0, 1.0);\n"
            + "            float2 v = float2(s2.x * w, s2.y * (1.0 - w)) + float2(0.0, 1.0e-4);\n"
            + "            specDir2 = normalize(v);\n"
            + "        }\n"
            + "\n"
            + "        // Fake-3D surface normal from the rounded-rect bevel.\n"
            + "        float minHalf = min(halfDim.x, halfDim.y);\n"
            + "        float bevelPx = max(minHalf * specDomeFrac, 1.0);\n"
            + "        float depthIn = max(-sdf, 0.0);\n"
            + "        float t       = clamp(depthIn / bevelPx, 0.0, 1.0);\n"
            + "        float n_cos   = 1.0 - t;\n"
            + "        float n_sin   = sqrt(max(1.0 - n_cos * n_cos, 0.0));      // float, not half: cancellation near n_cos~1\n"
            + "        float3 N      = normalize(float3(specDir2 * n_cos, n_sin + 1.0e-3));\n"
            + "\n"
            + "        float3 L = normalize(float3(lightVec, specLightZ));\n"
            + "        float3 V = float3(0.0, 0.0, 1.0);\n"
            + "\n"
            + "        // Moving focal hotspot: offset toward lightVec so the bright pool tracks tilt on both axes\n"
            + "        // (pitch=vertical, roll=horizontal). inside masks it off past the rim.\n"
            + "        float2 focal     = lightVec * (minHalf * specFocalK);\n"
            + "        float  poolR     = max(minHalf * specPoolFrac, 1.0);      // guard against zero-width smoothstep\n"
            + "        float  poolD     = length(p - focal);\n"
            + "        float  pool      = 1.0 - smoothstep(0.0, poolR, poolD);   // 1 at focal, 0 at rim\n"
            + "        float  inside    = 1.0 - smoothstep(-6.0, 0.0, sdf);\n"
            + "        float  focalPool = pool * pool * specStrength * specPoolGain * inside; // pool^2 = tighter core\n"
            + "\n"
            + "        // Broad body sheen (gentle modeling fill). float, not half: pow bands in fp16 (applies below too).\n"
            + "        float ndl       = max(dot(N, L), 0.0);\n"
            + "        float bodySheen = pow(ndl, specBodyPower) * specStrength * specBodyGain;\n"
            + "\n"
            + "        // Tight Blinn rim glint, confined to the rim band. max(specWidthPx, 1.0) guards the\n"
            + "        // zero-width (implementation-defined hard-step) smoothstep.\n"
            + "        float3 H       = normalize(L + V);\n"
            + "        float  rimBand = smoothstep(-max(specWidthPx, 1.0), 0.0, sdf);\n"
            + "        float  glint   = pow(max(dot(N, H), 0.0), specPower) * specStrength;\n"
            + "        float  rim     = glint * rimBand;\n"
            + "\n"
            + "        // Back-rim fill (opposite light, rim-locked, 1/4 weight).\n"
            + "        float3 Lb   = normalize(float3(-lightVec, specLightZ));\n"
            + "        float  back  = pow(max(dot(N, Lb), 0.0), specPower) * specStrength * rimBand * 0.25;\n"
            + "\n"
            + "        // Ordered dither to break 8-bit Mach banding on the body ramp. fract-bound the coord before\n"
            + "        // sin so the sin argument can't blow up on large lenses.\n"
            + "        float2 hp = fract((p / minHalf) * 0.5 + 0.5);             // bounded ~[0,1)\n"
            + "        float  dn = fract(sin(dot(hp, float2(12.9898, 78.233))) * 43758.5453) - 0.5;\n"
            + "\n"
            + "        // Linear body<->rim crossfade: rimMix=0 pure focal pool, rimMix=1 pure rim glint (legacy look).\n"
            + "        float body      = focalPool + bodySheen + dn * (1.0 / 255.0) * specStrength;\n"
            + "        float rimMix    = clamp(specRimMix, 0.0, 1.0);\n"
            + "        float highlight = body * (1.0 - rimMix) + (rim + back) * rimMix;\n"
            + "\n"
            + "        // Screen blend, clamped to [0,1] so it survives bright backgrounds and never exceeds 1.0.\n"
            + "        pixel.rgb += half3((1.0 - pixel.rgb) * clamp(highlight, 0.0, 1.0));\n"
            + "    }\n"
            + "\n"
            + "    // Anti-aliased edge transition\n"
            + "    float alpha = 1.0 - smoothstep(-SMOOTH_EDGE_PX * 0.5, SMOOTH_EDGE_PX * 0.5, sdf);\n"
            + "    half4 bg = fdmSample(xy);\n"
            + "    return mix(bg, pixel, alpha);\n"
            + "}"
            ;

    /** Nadeem 式：最轻的正弦扰动（没有真折射，但便宜） */
    static final String RIPPLE =
              "\n"
            + "uniform shader content;\n"
            + "// ── fdm 公共前奏（由 tools/gen_glass_shaders.py 注入）──\n"
            + "uniform float fdmCleanOn;\n"
            + "uniform float fdmCleanTol;\n"
            + "uniform float4 fdmCleanColor;\n"
            + "\n"
            + "half4 fdmSample(float2 p) {\n"
            + "    half4 c = content.eval(p);\n"
            + "    if (fdmCleanOn < 0.5) { return c; }\n"
            + "    float d = distance(float3(c.rgb), float3(fdmCleanColor.rgb));\n"
            + "    // 离背景色太远 ⇒ 认为是文字/图标 ⇒ 换成背景色\n"
            + "    return (d > fdmCleanTol) ? half4(half3(fdmCleanColor.rgb), c.a) : c;\n"
            + "}\n"
            + "\n"
            + "// ── 「边缘过渡」公共件（2026-10-02 主人：「颜色没有过渡也很生硬」）──\n"
            + "//   sd = 有符号距离（负值 = 内部、0 = 边缘）⇒ 颜色从边缘往里柔和衰减。\n"
            + "//   fdmFade   = 强度 0..1（滑杆）\n"
            + "//   fdmFadePx = 过渡距离（px）；「仅边缘」= 边缘带宽；「正常」= 按元素尺寸取。\n"
            + "uniform float fdmFade;\n"
            + "uniform float fdmFadePx;\n"
            + "\n"
            + "float fdmFadeFac(float sd) {\n"
            + "    float inner = clamp(-sd / max(fdmFadePx, 1.0), 0.0, 1.0);\n"
            + "    return 1.0 - fdmFade * inner;\n"
            + "}\n"
            + "// ──────────────────────────────────────────────\n"
            + "uniform float2 size;\n"
            + "uniform float strength;\n"
            + "\n"
            + "half4 main(float2 fragCoord) {\n"
            + "    float2 uv = fragCoord / size;\n"
            + "    float dx = sin(uv.y * 18.0) * strength * 6.0;\n"
            + "    float dy = cos(uv.x * 14.0) * strength * 4.0;\n"
            + "    return fdmSample(fragCoord + float2(dx, dy));\n"
            + "}"
            ;
}
